name: Manual autotests
on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v3

    - name: Install allure
      run: sudo npm install -g allure-commandline

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/test_main.py -v -s --alluredir=allure-results

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report
        zip -r allure-report.zip allure-report

    - name: Send Allure report to Telegram
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -F chat_id=$CHAT_ID -F document=@allure-report.zip "https://api.telegram.org/bot$BOT_TOKEN/sendDocument"
