name: Manual autotests
on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v3

    - name: Install allure
      run: sudo npm install -g allure-commandline

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
    - name: Run tests
      run: pytest tests/test_main.py -v -s --alluredir allure-results

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - name: Send Allure report to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        REPORT_FILE="allure-report/index.html"
        curl -F "document=@${REPORT_FILE}" \
             "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument"

